### ISSUE TITLE
Unable to load KYNode

### ISSUE THREAD

**Issue by Kaotic3** [yorkane/ComfyUI-KYNode#1]
I grabbed a workflow from a Youtube video using this node.  I loaded the workflow and then loaded all the missing nodes.

This one won't load.  I have run updates on the UI and the python dependencies to no avail.

The reason it won't load is that you introduced openai_VLM.py which requires dotenv - but this appears not to be a requirement for or loaded up with ComfyUI as standard - I am receiving the error:

`
File "F:\10 AI Images\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KYNode\openai_VLM.py", line 7, in <module>
    from dotenv import load_dotenv
ModuleNotFoundError: No module named 'dotenv'
`

This is not an error I receive for any other module or why running ComfyUI.

I suspect I can fix it but you may want to either add it as a requirement for ComfyUI or remove it from the openai_VLM.py.

**Comment by Kaotic3** [comment]
As a work around if you go to the ComfyUI folder you can use:

`.\python_embeded\python.exe -m pip install python-dotenv`

Which will install dotenv in the right place so that this node will now work.  Adding it to requirements doesn't help, because it says it is satisfied based on your global - it won't add it here.

**Comment by perobueno** [comment]
I am also having this issue.
I tried installing that and it installed okay, but It's still failing to import.

   0.0 seconds (IMPORT FAILED): x:\xx\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KYNode

**Comment by yorkane** [comment]
requirements.txt updated,
I have removed dotenv reference,
